#!/bin/sh /etc/rc.common

START=99
SERVICE_USE_PID=1
USE_PROCD=1
IC_BIN=/bin/hello_ubus


#. /lib/functions.sh

start_service() {
	procd_open_instance
	
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param command  $IC_BIN
	procd_set_param respawn
	
	procd_close_instance
}


reload_service() {
	restart
}
